# Generated by Django 5.2.4 on 2025-07-26 06:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_image', models.ImageField(upload_to='profile_image')),
                ('about_heading', models.CharField(default='Full Stack Web Developer', max_length=100)),
                ('about_intro', models.TextField()),
                ('about_short_text', models.TextField(help_text='Italic line under heading')),
                ('about_birthday', models.DateField()),
                ('about_website', models.URLField()),
                ('about_phone', models.CharField(max_length=20)),
                ('about_city', models.CharField(max_length=100)),
                ('about_age', models.IntegerField()),
                ('about_degree', models.CharField(max_length=50)),
                ('about_email', models.EmailField(max_length=254)),
                ('about_freelance', models.CharField(max_length=50)),
                ('about_detail', models.TextField(help_text='Bottom paragraph in About section')),
            ],
            options={
                'verbose_name': '03 - About Section',
                'verbose_name_plural': '03 - About Section',
            },
        ),
        migrations.CreateModel(
            name='PortfolioSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(help_text='For example: HTML, CSS, JS, WordPress etc', max_length=100)),
                ('skill_short_des', models.TextField(help_text='Short description of the skill')),
                ('skill_expertise', models.IntegerField(help_text='Expertise Percentage (value between 1 - 100)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'verbose_name': '05 - Skills Section',
                'verbose_name_plural': '05 - Skills Section',
            },
        ),
        migrations.CreateModel(
            name='PortfolioStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stats_number', models.IntegerField()),
                ('stats_text', models.CharField(max_length=100)),
                ('stats_icon', models.ImageField(upload_to='stats_icons/')),
                ('show_plus', models.BooleanField(default=False, help_text='Check to show + after the number')),
            ],
            options={
                'verbose_name': '04 - Stats Section',
                'verbose_name_plural': '04 - Stats Section',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=50)),
                ('profile_img_header', models.ImageField(upload_to='profile_image')),
                ('profile_skills', models.TextField(help_text='Comma-separated values, e.g. Full Stack Web Developer, Python, Django')),
            ],
            options={
                'verbose_name': '01 - Site Profile',
                'verbose_name_plural': '01 - Site Profile',
            },
        ),
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=100)),
                ('icon', models.ImageField(upload_to='social_icons/')),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': '02 - Social Media Links Header',
                'verbose_name_plural': '02 - Social Media Links Header',
            },
        ),
    ]
