# Generated by Django 5.2.4 on 2025-07-27 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioResumeDes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_des', models.TextField(help_text='Resume Description Under Resume Heading')),
            ],
            options={
                'verbose_name': '06 - Resume Description',
                'verbose_name_plural': '06 - Resume Description',
            },
        ),
        migrations.CreateModel(
            name='PortfolioServiceDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_des', models.TextField(help_text='Services Description Under Services Heading')),
            ],
            options={
                'verbose_name': '09 - Services Description',
                'verbose_name_plural': '09 - Services Description',
            },
        ),
        migrations.CreateModel(
            name='PortfolioServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('service_icon', models.ImageField(upload_to='service_icons/')),
                ('service_short_detail', models.TextField(help_text='Short paragraph for service card')),
                ('Service_long_detail', models.TextField(help_text='long para graph for service detail page')),
                ('service_description_1', models.TextField(blank=True, help_text='Description for service detail may be empty if not needed', null=True)),
                ('service_description_2', models.TextField(blank=True, help_text='Description for service detail may be empty if not needed', null=True)),
                ('service_description_3', models.TextField(blank=True, help_text='Description for service detail may be empty if not needed', null=True)),
                ('service_description_4', models.TextField(blank=True, help_text='Description for service detail may be empty if not needed', null=True)),
                ('service_description_5', models.TextField(blank=True, help_text='Description for service detail may be empty if not needed', null=True)),
                ('service_extra_detailed', models.TextField(help_text='Extra detailed description for service detail page under descriotion')),
                ('service_slug', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': '10 - Services Section',
                'verbose_name_plural': '10 - Services Section',
            },
        ),
        migrations.CreateModel(
            name='ResumeEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edu_degree', models.CharField(max_length=200)),
                ('edu_start_year', models.IntegerField()),
                ('edu_end_year', models.IntegerField()),
                ('edu_institute', models.CharField(max_length=200)),
                ('edu_description', models.TextField()),
            ],
            options={
                'verbose_name': '07 - Resume - Education',
            },
        ),
        migrations.CreateModel(
            name='ResumeExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('job_start_year', models.CharField(max_length=10)),
                ('job_end_year', models.CharField(max_length=10)),
                ('job_company', models.CharField(max_length=200)),
                ('job_description_1', models.TextField(blank=True, help_text='Resume Description may be empty if not needed', null=True)),
                ('job_description_2', models.TextField(blank=True, help_text='Resume Description may be empty if not needed', null=True)),
                ('job_description_3', models.TextField(blank=True, help_text='Resume Description may be empty if not needed', null=True)),
                ('job_description_4', models.TextField(blank=True, help_text='Resume Description may be empty if not needed', null=True)),
                ('job_description_5', models.TextField(blank=True, help_text='Resume Description may be empty if not needed', null=True)),
            ],
            options={
                'verbose_name': '08 - Resume - Experience',
            },
        ),
        migrations.RemoveField(
            model_name='portfolioskills',
            name='skill_short_des',
        ),
    ]
