# Generated by Django 5.2.4 on 2025-07-27 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_portfolioresumedes_portfolioservicedescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioservices',
            name='service_image',
            field=models.ImageField(default='service_images/default.jpg', help_text='image for detail Page', upload_to='service_images/'),
        ),
    ]
