# Generated by Django 5.2.4 on 2025-07-27 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_portfolioservices_service_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioTestimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonial_name', models.CharField(max_length=100)),
                ('testimonial_text', models.TextField()),
                ('testimonial_img', models.ImageField(upload_to='testimonial_images/')),
            ],
            options={
                'verbose_name': '11 - Testimonial Section',
                'verbose_name_plural': '11 - Testimonial Section',
            },
        ),
    ]
