# Generated by Django 5.2.4 on 2025-07-27 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_portfoliotestimonials'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliotestimonials',
            name='testimonial_company',
            field=models.CharField(default='none'),
        ),
    ]
