# Generated by Django 5.2.4 on 2025-07-27 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_portfoliotestimonials_testimonial_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioservices',
            name='service_image',
            field=models.ImageField(help_text='image for detail Page', upload_to='service_images/'),
        ),
        migrations.AlterField(
            model_name='portfoliotestimonials',
            name='testimonial_company',
            field=models.CharField(),
        ),
    ]
