# Generated by Django 5.2.4 on 2025-07-27 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_alter_portfolioservices_service_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioPortfolioDes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_des', models.TextField()),
            ],
            options={
                'verbose_name': '12 - Portfolio Description',
                'verbose_name_plural': '12 - Portfolio Description',
            },
        ),
    ]
