# Generated by Django 5.2.4 on 2025-07-27 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_portfolioportfoliodes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioPortfolioFilters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '13 - Portfolio Filters',
                'verbose_name_plural': '13 - Portfolio Filters',
            },
        ),
    ]
