# Generated by Django 5.2.4 on 2025-07-27 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_portfolioportfoliofilters'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioportfoliofilters',
            name='filter_display_text',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
