# Generated by Django 5.2.4 on 2025-07-27 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_portfolioportfoliofilters_filter_display_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioportfoliofilters',
            name='filter_display_text',
            field=models.CharField(max_length=100),
        ),
    ]
