# Generated by Django 5.2.4 on 2025-07-27 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_alter_portfolioportfoliofilters_filter_display_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PortfolioPortfolioFilters',
        ),
    ]
