# Generated by Django 5.2.4 on 2025-07-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_delete_portfolioportfoliofilters'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_name', models.SlugField(help_text='Used as CSS class. Eg: filter-app', unique=True)),
                ('filter_display_text', models.CharField(help_text='Text to show in filter menu. Eg: App', max_length=100)),
            ],
            options={
                'verbose_name': '13 - Portfolio Filters',
                'verbose_name_plural': '13 - Portfolio Filters',
            },
        ),
    ]
