# Generated by Django 5.2.4 on 2025-07-27 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0013_portfolioitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolioitem',
            options={'verbose_name': '14 - Portfolio Items', 'verbose_name_plural': '14 - Portfolio Items'},
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='port_item_title',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='portfolioservices',
            name='service_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
