# Generated by Django 5.2.4 on 2025-07-27 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0014_alter_portfolioitem_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PortfolioItem',
        ),
    ]
