# Generated by Django 5.2.4 on 2025-07-27 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0015_delete_portfolioitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_item_title', models.CharField(max_length=200, unique=True)),
                ('port_item_image', models.ImageField(upload_to='portfolio/')),
                ('port_item_description', models.TextField()),
                ('port_item_detail_image_1', models.ImageField(blank=True, help_text='Image may be empty if not needed', null=True, upload_to='portfolio/')),
                ('port_item_detail_image_2', models.ImageField(blank=True, help_text='Image may be empty if not needed', null=True, upload_to='portfolio/')),
                ('port_item_detail_image_3', models.ImageField(blank=True, help_text='Image may be empty if not needed', null=True, upload_to='portfolio/')),
                ('port_item_detail_image_4', models.ImageField(blank=True, help_text='Image may be empty if not needed', null=True, upload_to='portfolio/')),
                ('port_item_detail_image_5', models.ImageField(blank=True, help_text='Image may be empty if not needed', null=True, upload_to='portfolio/')),
                ('port_item_detail_description', models.TextField(default='10-06-2023')),
                ('port_item_created_date', models.DateField()),
                ('port_item_slug', models.CharField(blank=True, max_length=1000, null=True)),
                ('port_item_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.portfoliofilter')),
            ],
            options={
                'verbose_name': '14 - Portfolio Items',
                'verbose_name_plural': '14 - Portfolio Items',
            },
        ),
    ]
