# Generated by Django 5.2.4 on 2025-07-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0016_portfolioitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='port_item_detail_client',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='port_item_detail_project_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='port_item_detail_description',
            field=models.TextField(),
        ),
    ]
