# Generated by Django 5.2.4 on 2025-07-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0018_alter_portfolioitem_port_item_detail_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='port_item_detail_client',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='port_item_detail_project_url',
            field=models.URLField(),
        ),
    ]
