# Generated by Django 5.2.4 on 2025-07-27 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0019_alter_portfolioitem_port_item_detail_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioservices',
            name='service_description_1',
        ),
        migrations.RemoveField(
            model_name='portfolioservices',
            name='service_description_2',
        ),
        migrations.RemoveField(
            model_name='portfolioservices',
            name='service_description_3',
        ),
        migrations.RemoveField(
            model_name='portfolioservices',
            name='service_description_4',
        ),
        migrations.RemoveField(
            model_name='portfolioservices',
            name='service_description_5',
        ),
        migrations.RemoveField(
            model_name='resumeexperience',
            name='job_description_1',
        ),
        migrations.RemoveField(
            model_name='resumeexperience',
            name='job_description_2',
        ),
        migrations.RemoveField(
            model_name='resumeexperience',
            name='job_description_3',
        ),
        migrations.RemoveField(
            model_name='resumeexperience',
            name='job_description_4',
        ),
        migrations.RemoveField(
            model_name='resumeexperience',
            name='job_description_5',
        ),
        migrations.CreateModel(
            name='PortfolioServicesDetailDescrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_description', models.TextField(help_text='Description for service detail add ass many as needed')),
                ('service_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.portfolioservices')),
            ],
            options={
                'verbose_name': '10 - Services Section Detail Descrition',
                'verbose_name_plural': '10 - Services Section',
            },
        ),
        migrations.CreateModel(
            name='ResumeExperienceDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_description', models.TextField(help_text='Resume Description add as many as needed')),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.resumeexperience')),
            ],
            options={
                'verbose_name': '08 - Resume - Experience Description',
                'verbose_name_plural': '08 - Resume - Experience Description',
            },
        ),
    ]
