# Generated by Django 5.2.4 on 2025-07-27 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0020_remove_portfolioservices_service_description_1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolioitem',
            options={'verbose_name': '14-1 - Portfolio Items', 'verbose_name_plural': '14-1 - Portfolio Items'},
        ),
        migrations.AlterModelOptions(
            name='portfolioservices',
            options={'verbose_name': '10-1 - Services Section', 'verbose_name_plural': '10-1 - Services Section'},
        ),
        migrations.AlterModelOptions(
            name='portfolioservicesdetaildescrition',
            options={'verbose_name': '10-2 - Services Section Detail Descrition', 'verbose_name_plural': '10-2 - Services Section Detail Description'},
        ),
        migrations.AlterModelOptions(
            name='resumeexperience',
            options={'verbose_name': '08-1 - Resume - Experience', 'verbose_name_plural': '08-1 - Resume - Experience'},
        ),
        migrations.AlterModelOptions(
            name='resumeexperiencedescription',
            options={'verbose_name': '08-2 - Resume - Experience Description', 'verbose_name_plural': '08-2 - Resume - Experience Description'},
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='port_item_detail_image_1',
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='port_item_detail_image_2',
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='port_item_detail_image_3',
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='port_item_detail_image_4',
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='port_item_detail_image_5',
        ),
        migrations.CreateModel(
            name='PortfolioItemDetailImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_item_detail_image', models.ImageField(upload_to='portfolio_detail/')),
                ('port_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.portfolioitem')),
            ],
            options={
                'verbose_name': '14-2 - Portfolio Item Detail Images',
                'verbose_name_plural': '14-2 - Portfolio Item Detail Images',
            },
        ),
    ]
