# Generated by Django 5.2.4 on 2025-07-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0021_alter_portfolioitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='port_item_detail_project_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
