# Generated by Django 5.2.4 on 2025-07-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0022_alter_portfolioitem_port_item_detail_project_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfoLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_embed_map', models.TextField(help_text='Paste Google Maps iframe embed code here')),
            ],
            options={
                'verbose_name': '15 Contact Location',
                'verbose_name_plural': '15 Contact Location',
            },
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='port_item_detail_project_url',
            field=models.URLField(blank=True, help_text='Leave empty if not needed', null=True),
        ),
    ]
