# Generated by Django 5.2.4 on 2025-07-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0023_contactinfolocation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_des', models.TextField()),
            ],
            options={
                'verbose_name': '15 Contact Description',
                'verbose_name_plural': '15 Contact Description',
            },
        ),
        migrations.AlterModelOptions(
            name='contactinfolocation',
            options={'verbose_name': '16 Contact Location', 'verbose_name_plural': '16 Contact Location'},
        ),
    ]
