# Generated by Django 5.2.4 on 2025-07-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0024_contactdescription_alter_contactinfolocation_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDataByUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con_name', models.CharField(max_length=100)),
                ('con_email', models.EmailField(max_length=254)),
                ('con_sub', models.CharField(max_length=50)),
                ('con_msg', models.CharField(max_length=500)),
            ],
        ),
    ]
