# Generated by Django 5.2.4 on 2025-07-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0025_contactdatabyuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactdatabyuser',
            options={'verbose_name': '17 Contact Data By User', 'verbose_name_plural': '17 Contact Data By User'},
        ),
        migrations.AlterField(
            model_name='contactdatabyuser',
            name='con_msg',
            field=models.TextField(),
        ),
    ]
